version: "1.0"
services:
  web:
    image: allanrodriguesmachado/php-nginx-node:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - net_principal
    volumes:
      - .:/var/www
      - ./docker/nginx/sites:/etc/nginx/sites-available
    ports:
      - "80:80"
networks:
  net_principal: